project_id = "oqrqypuulgeqzjcgqruw"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.send-retainer-email]
    verify_jwt = false
  [functions.resend-webhook]
    verify_jwt = false
  [functions.dispatch-webhook]
    verify_jwt = false
  [functions.portal-view]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.connect-stripe]
    verify_jwt = false
  [functions.connect-stripe-callback]
    verify_jwt = false
